# Site settings
title: Mon CV 
description: ddbullfrog's CV
favicon: /assets/img/gp.jpeg
baseurl: http://gregoire.pouget.free.fr/cv/
url: http://gregoire.pouget.free.fr/cv/
rss_url: /pages/atom.xml

# Collections
collections:
  - experiences
  - degrees
  
# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Grégoire Pouget
  title: ONG, développement, information, numérique
  address: Paris, France
  email: gregoire [at] byl.fr
  link: https://byl.fr
  weibo:
  github: barbayellow
  linkedin: gregoirepouget
  twitter: barbayellow
  gavatar: /resumecard/assets/img/gp.jpeg
  languages:
    - language1:
      name: Français
      proficiency: Courant
    - language2:
      name: English
      proficiency: Courant
    - language3:
      name: PHP
      proficiency: Courant
    - language4:
      name: Python
      proficiency: Profesionnel
  skills:
    - skill1:
      name: Gestion de projet
      percentage: 100%
    - skill2:
      name: Management
      percentage: 90%
    - skill3:
      name: Plaidoyer
      percentage: 70%
    - skill4:
      name: Formation animation
      percentage: 70%
